splashes = [
	"websites a stupid",
	"your friendly neighborhood idiot",
	"over 3000 lives",
	"forgot a semicolon",
	"used css, and lived",
	"has a potato stuck in his eye",
	"will finish his first project in 2197",
	"makes simple things like growls",
	"is a best guy thing",
	".php.zip.html.flv.rar.7z.png.jade.exe.gif.mov.js",
	"dududududude!",
	"20% blockier",
	"really loves spoons",
	"apples are cool",
	"it's a type of cat",
	"likes to smash faec in coocky",
	"ae",
	"really hates periods",
	"thought a php file was his friend robert",
	"doesn't care about your hair",
	"is actually a cow",
	"it can't crash if it never loads",
	"squishy splatoonians",
	"*filler splash*",
	"not a kid or a squid",
	"pizza is good",
	"error 404, splash not found",
	"likes to fly away",
	"no u",
	"ate your face",
	"actually never had an apple stick",
	"the b is capital",
	"spoony",
	"tell me about this \"fixing\" thing",
	"what is life",
	"bahstep",
	"is secretly creator cat",
	"math.floor(math.round(math.floor(math.round())))",
	"can't firefox"
];

num = Math.floor(Math.random() * splashes.length);
document.write(splashes[num]);
